[package]
name = "sccache"
version = "0.2.8-alpha.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>", "Alex Crichton <alex@alexcrichton.com>"]
license = "Apache-2.0"
description = "Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids compilation when possible, storing a cache in a remote storage using the S3 API."
repository = "https://github.com/mozilla/sccache/"
readme = "README.md"
categories = ["command-line-utilities", "development-tools::build-utils"]
keywords = ["ccache"]

[badges]
travis-ci = { repository = "mozilla/sccache" }
appveyor = { repository = "mozilla/sccache" }

[dependencies]
base64 = "0.9.0"
bincode = "0.9"
byteorder = "1.0"
chrono = { version = "0.3", optional = true }
clap = "2.23.0"
env_logger = "0.4"
error-chain = { version = "0.11", default-features = false }
filetime = "0.1"
futures = "0.1.11"
futures-cpupool = "0.1"
hyper = { version = "0.11", optional = true }
hyper-tls = { version = "0.1", optional = true }
jobserver = "0.1"
jsonwebtoken = { version = "4.0", optional = true }
libc = "0.2.10"
local-encoding = "0.2.0"
log = "0.3.6"
lmdb  = { version = "0.8.0", optional = true }
lru-disk-cache = { path = "lru-disk-cache", version = "0.2.0" }
memcached-rs = { version = "0.1" , optional = true }
native-tls = "0.1"
num_cpus = "1.0"
number_prefix = "0.2.5"
openssl = { version = "0.9", optional = true }
redis = { version = "0.8.0", optional = true }
regex = "0.2"
retry = "0.4.0"
ring = "0.12.1"
rust-crypto = { version = "0.2.36", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
strip-ansi-escapes = "0.1"
tempdir = "0.3.4"
tempfile = "2.1.5"
time = "0.1.35"
tokio-core = "0.1.6"
tokio-io = "0.1"
tokio-process = "0.1"
tokio-proto = "0.1"
tokio-serde-bincode = "0.1"
tokio-service = "0.1"
tokio-tls = "0.1"
uuid = { version = "0.6", features = ["v4"] }
url = { version = "1.0", optional = true }
which = "1.0"
zip = { version = "=0.2.3", default-features = false }
lazy_static = "1.0.0"
atty = "0.2.6"
directories = "0.8.4"

[dev-dependencies]
assert_cli = "0.5"
cc = "1.0"
itertools = "0.7"

[target.'cfg(unix)'.dependencies]
daemonize = "0.2.3"
tokio-uds = "0.1"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.2"
mio-named-pipes = "0.1"

[features]
default = ["s3", "the_lmdb"]
all = ["redis", "s3", "memcached", "gcs", "azure"]
# gcs requires openssl, which is a pain on Windows.
all-windows = ["redis", "s3", "memcached", "azure"]
azure = ["chrono", "hyper", "hyper-tls", "rust-crypto"]
s3 = ["chrono", "hyper", "hyper-tls", "rust-crypto", "simple-s3"]
simple-s3 = []
gcs = ["chrono", "hyper", "hyper-tls", "jsonwebtoken", "openssl", "url"]
memcached = ["memcached-rs"]
the_lmdb = ["lmdb"]
# Enable features that require unstable features of Nightly Rust.
unstable = []

[workspace]
exclude = ["tests/test-crate"]
